# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://smc.sourceforge.net/)
# from file : GPCAlgGlobFSM.sm

import statemap


class GPCAlgGlobProcState(statemap.State):

    def Entry(self, fsm):
        pass

    def Exit(self, fsm):
        pass

    def InitDone(self, fsm):
        self.Default(fsm)

    def InitError(self, fsm, msg):
        self.Default(fsm)

    def MPCActive(self, fsm):
        self.Default(fsm)

    def MPCDone(self, fsm):
        self.Default(fsm)

    def MPCImpossible(self, fsm, msg):
        self.Default(fsm)

    def MPCInactif(self, fsm):
        self.Default(fsm)

    def OPCWrite(self, fsm, msg):
        self.Default(fsm)

    def OPCWriteError(self, fsm, msg):
        self.Default(fsm)

    def Reset(self, fsm):
        self.Default(fsm)

    def TrigError(self, fsm, msg):
        self.Default(fsm)

    def TrigOK(self, fsm, dt):
        self.Default(fsm)

    def VarsError(self, fsm, msg):
        self.Default(fsm)

    def VarsOK(self, fsm):
        self.Default(fsm)

    def Default(self, fsm):
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write('TRANSITION   : Default\n')
        msg = "\n\tState: %s\n\tTransition: %s" % (
            fsm.getState().getName(), fsm.getTransition())
        raise statemap.TransitionUndefinedException, msg

class GPCMap_Default(GPCAlgGlobProcState):

    def Default(self, fsm):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.Default\n")

        endState = fsm.getState()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.Default.Default()\n")

        fsm.clearState()
        try:
            ctxt.logIgnored()
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.Default.Default()\n")

            fsm.setState(endState)

class GPCMap_INIT(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.initInit()

    def InitDone(self, fsm):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.INIT\n")

        if ctxt.isInitDone() :
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.INIT.InitDone()\n")

            fsm.clearState()
            try:
                ctxt.doInitRTrigParam()
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.INIT.InitDone()\n")

                fsm.setState(GPCMap.getRTrig)
                fsm.getState().Entry(fsm)
        else:
            endState = fsm.getState()
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.INIT.InitDone()\n")

            fsm.clearState()
            try:
                ctxt.doInit()
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.INIT.InitDone()\n")

                fsm.setState(endState)


    def InitError(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.INIT\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.INIT.InitError(msg)\n")

        fsm.clearState()
        try:
            ctxt.doWarning(msg)
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.INIT.InitError(msg)\n")

            fsm.setState(GPCMap.GPCisOffline)
            fsm.getState().Entry(fsm)

class GPCMap_GPCisOffline(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doSetGPCOffline()

    def Reset(self, fsm):
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.GPCisOffline\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.GPCisOffline.Reset()\n")

        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.GPCisOffline.Reset()\n")

        fsm.setState(GPCMap.INIT)
        fsm.getState().Entry(fsm)

class GPCMap_getRTrig(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doRTrigInit()

    def Exit(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doRTrigStop()

    def TrigError(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.getRTrig\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.getRTrig.TrigError(msg)\n")

        fsm.clearState()
        try:
            ctxt.doWarning(msg)
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.getRTrig.TrigError(msg)\n")

            fsm.setState(GPCMap.GPCisOffline)
            fsm.getState().Entry(fsm)

    def TrigOK(self, fsm, dt):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.getRTrig\n")

        if ctxt.isNotSync() :
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.getRTrig.TrigOK(dt)\n")

            fsm.clearState()
            try:
                ctxt.doUpdateRTrigParam(dt)
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.getRTrig.TrigOK(dt)\n")

                fsm.setState(GPCMap.readOPCVars)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.getRTrig.TrigOK(dt)\n")

            # No actions.
            pass
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.getRTrig.TrigOK(dt)\n")

            fsm.setState(GPCMap.readOPCVars)
            fsm.getState().Entry(fsm)


class GPCMap_readOPCVars(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doReadOPC()

    def VarsError(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.readOPCVars\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.readOPCVars.VarsError(msg)\n")

        fsm.clearState()
        try:
            ctxt.doWarning(msg)
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.readOPCVars.VarsError(msg)\n")

            fsm.setState(GPCMap.GPCisOffline)
            fsm.getState().Entry(fsm)

    def VarsOK(self, fsm):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.readOPCVars\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.readOPCVars.VarsOK()\n")

        fsm.clearState()
        try:
            ctxt.doUpdateParam()
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.readOPCVars.VarsOK()\n")

            fsm.setState(GPCMap.checkSysStates)
            fsm.getState().Entry(fsm)

class GPCMap_checkSysStates(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doCheckSysStates()

    def MPCActive(self, fsm):
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.checkSysStates\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.checkSysStates.MPCActive()\n")

        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.checkSysStates.MPCActive()\n")

        fsm.setState(GPCMap.runMPC)
        fsm.getState().Entry(fsm)

    def MPCImpossible(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.checkSysStates\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.checkSysStates.MPCImpossible(msg)\n")

        fsm.clearState()
        try:
            ctxt.doWarning(msg)
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.checkSysStates.MPCImpossible(msg)\n")

            fsm.setState(GPCMap.GPCisOffline)
            fsm.getState().Entry(fsm)

    def MPCInactif(self, fsm):
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.checkSysStates\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.checkSysStates.MPCInactif()\n")

        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.checkSysStates.MPCInactif()\n")

        fsm.setState(GPCMap.getRTrig)
        fsm.getState().Entry(fsm)

class GPCMap_runMPC(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doRunMPC()

    def MPCDone(self, fsm):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.runMPC\n")

        if ctxt.isNoOPCWrite() :
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.runMPC.MPCDone()\n")

            fsm.clearState()
            try:
                ctxt.doLogMPCResults()
                ctxt.doResetWriteVars()
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.runMPC.MPCDone()\n")

                fsm.setState(GPCMap.getRTrig)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.runMPC.MPCDone()\n")

            fsm.clearState()
            try:
                ctxt.doLogMPCResults()
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.runMPC.MPCDone()\n")

                fsm.setState(GPCMap.writeOPCVars)
                fsm.getState().Entry(fsm)


    def MPCImpossible(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.runMPC\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.runMPC.MPCImpossible(msg)\n")

        fsm.clearState()
        try:
            ctxt.doWarning(msg)
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.runMPC.MPCImpossible(msg)\n")

            fsm.setState(GPCMap.GPCisOffline)
            fsm.getState().Entry(fsm)

class GPCMap_writeOPCVars(GPCMap_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.doWriteOPCInit()

    def OPCWrite(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.writeOPCVars\n")

        if ctxt.isOPCWriteOK() :
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.writeOPCVars.OPCWrite(msg)\n")

            fsm.clearState()
            try:
                ctxt.doWTrigInit()
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.writeOPCVars.OPCWrite(msg)\n")

                fsm.setState(GPCMap.getRTrig)
                fsm.getState().Entry(fsm)
        elif ctxt.isOPCWriteError() :
            fsm.getState().Exit(fsm)
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.writeOPCVars.OPCWrite(msg)\n")

            fsm.clearState()
            try:
                ctxt.doWarning(msg)
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.writeOPCVars.OPCWrite(msg)\n")

                fsm.setState(GPCMap.GPCisOffline)
                fsm.getState().Entry(fsm)
        else:
            endState = fsm.getState()
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.writeOPCVars.OPCWrite(msg)\n")

            fsm.clearState()
            try:
                ctxt.doWriteOPC()
            finally:
                if fsm.getDebugFlag() == True:
                    fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.writeOPCVars.OPCWrite(msg)\n")

                fsm.setState(endState)


    def OPCWriteError(self, fsm, msg):
        ctxt = fsm.getOwner()
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("LEAVING STATE   : GPCMap.writeOPCVars\n")

        fsm.getState().Exit(fsm)
        if fsm.getDebugFlag() == True:
            fsm.getDebugStream().write("ENTER TRANSITION: GPCMap.writeOPCVars.OPCWriteError(msg)\n")

        fsm.clearState()
        try:
            ctxt.doWarning(msg)
        finally:
            if fsm.getDebugFlag() == True:
                fsm.getDebugStream().write("EXIT TRANSITION : GPCMap.writeOPCVars.OPCWriteError(msg)\n")

            fsm.setState(GPCMap.GPCisOffline)
            fsm.getState().Entry(fsm)

class GPCMap(object):

    INIT = GPCMap_INIT('GPCMap.INIT', 0)
    GPCisOffline = GPCMap_GPCisOffline('GPCMap.GPCisOffline', 1)
    getRTrig = GPCMap_getRTrig('GPCMap.getRTrig', 2)
    readOPCVars = GPCMap_readOPCVars('GPCMap.readOPCVars', 3)
    checkSysStates = GPCMap_checkSysStates('GPCMap.checkSysStates', 4)
    runMPC = GPCMap_runMPC('GPCMap.runMPC', 5)
    writeOPCVars = GPCMap_writeOPCVars('GPCMap.writeOPCVars', 6)
    Default = GPCMap_Default('GPCMap.Default', -1)

class GPCAlgGlobProc_sm(statemap.FSMContext):

    def __init__(self, owner):
        statemap.FSMContext.__init__(self, GPCMap.INIT)
        self._owner = owner

    def __getattr__(self, attrib):
        def trans_sm(*arglist):
            self._transition = attrib
            getattr(self.getState(), attrib)(self, *arglist)
            self._transition = None
        return trans_sm

    def enterStartState(self):
        self._state.Entry(self)

    def getOwner(self):
        return self._owner

# Local variables:
#  buffer-read-only: t
# End:
